# Generated by Django 5.1.2 on 2024-10-17 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_first_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='year',
            field=models.IntegerField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='title',
            field=models.TextField(max_length=250),
        ),
    ]
