# Generated by Django 5.1.2 on 2024-10-17 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_first_app', '0004_author_book_authors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='bith_date',
            new_name='birth_date',
        ),
    ]
